### ISSUE TITLE
Copyright notice not aligned correctly

### ISSUE THREAD

**Issue by jplatte** [freifunkks/ffmap-ng#1]
It seems the copyright notice should be in the lower-right corner, but it seems to be some fixed amount of space higher.

![screenshot](https://cloud.githubusercontent.com/assets/951129/6167591/18e6db6a-b2bd-11e4-957e-53d50a9824d5.png)

**Comment by Gottox** [comment]
We will replace ffmap-ng with ffmap-d3 once ffmap-d3 works properly anyway.
